#!/bin/bash
cp gitconfig ~/.gitconfig
cp vimrc ~/.vimrc
#
echo "alias ll='ls -l'" >> ~/.bashrc
echo "alias la='ls -al'" >> ~/.bashrc

#install ns-2.35
sh install-ns-2.35 |tee install-ns-2.35.log

#install python-matplotlib
sh install-py-matplotlib |tee install-py-matplotlib.log

#install mysql
sh install-mysql |tee install-mysql.log

#install django
sh install-django |tee install-django.log
